application: stmikspbchat
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /res
  static_dir: res
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: main.py

